trigger:
- main

pool:
  name: Default

parameters:
  - name: groups
    displayName: 'Select groups'
    type: string
    default: 'Smoke'
    values:
      - Smoke
      - Sanity
      - Regression
  - name: prod
    displayName: 'Select prod'
    type: string
    default: 'api'
    values:
      - api
      - web
  - name: env
    displayName: 'Select env'
    type: string
    default: 'devopsqa'
    values:
      - test
      - UAT
      - Prod
      - devopsqa
      - devopsuat
      - devopsprod   

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.9.7'
#     architecture: 'x64'
#     pathToPython: 'C:\Program Files\Python39\python.exe'

- script: |
    python -m pip install --upgrade pip
    pip install selenium    
  displayName: 'Install Dependencies'

- script: mvn -version
  displayName: 'Check Maven version'
# - task: UseDotNet@2
#   inputs:
#     packageType: 'Maven'
#     versionSpec: '3.9.8' 
#     mavenHomePath: 'F:\apache-maven-3.9.8'
    
# # Execute Whole Test Package
# - script: |
#     mvn clean test -Dgroups=Smoke,setUp -Dprod=web -Denv=uat -Dregion=us -Dtest=web.web_TestCases.**
#   displayName: 'Run Whole Test Package'

# # Execute Single Whole Test Class
# - script: |
#     mvn clean test -Dgroups=Smoke,setUp -Dprod=web -Denv=uat -Dregion=us -Dtest=web.web_TestCases.login_Tests.**
#   displayName: 'Run Single Whole Test Class'

# # Execute Single Test Method
# - script: |
#     mvn clean test -Dgroups=Smoke,setUp -Dprod=web -Denv=uat -Dregion=us -Dtest=web.web_TestCases.login_Tests#administrator_User_Login_Successfully
#   displayName: 'Run Single Test Method'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '/surefire-reports/TEST-*.xml'
#     mergeTestResults: true
#     testRunTitle: 'QAAutomation Test Results'